/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu_Inicio;
import registro_productos.registrar_productos;
import registro_recetas.registrar_recetas;
/**
 *
 * @author PC
 */
public class menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Items
     */
    public menu_principal() {
        initComponents();
        txtPrueba.setText("verificador de conexiones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_compras2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_RegistrarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_inventario = new javax.swing.JButton();
        btn_largate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPrueba = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        btn_ingredientes = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_compras2.setBackground(new java.awt.Color(226, 115, 150));
        btn_compras2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn_compras2.setForeground(new java.awt.Color(234, 242, 215));
        btn_compras2.setText("▶Ver inventario");
        btn_compras2.setBorder(null);
        btn_compras2.setBorderPainted(false);
        btn_compras2.setContentAreaFilled(false);
        btn_compras2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_compras2.setDefaultCapable(false);
        btn_compras2.setFocusPainted(false);
        btn_compras2.setFocusable(false);
        btn_compras2.setInheritsPopupMenu(true);
        btn_compras2.setRequestFocusEnabled(false);
        btn_compras2.setRolloverEnabled(false);
        btn_compras2.setVerifyInputWhenFocusTarget(false);
        btn_compras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compras2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 115, 150));

        jPanel2.setBackground(new java.awt.Color(234, 242, 215));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PASTELERIA");

        btn_RegistrarProducto.setBackground(new java.awt.Color(226, 115, 150));
        btn_RegistrarProducto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn_RegistrarProducto.setForeground(new java.awt.Color(234, 242, 215));
        btn_RegistrarProducto.setText("> Consultar Productos");
        btn_RegistrarProducto.setBorder(null);
        btn_RegistrarProducto.setBorderPainted(false);
        btn_RegistrarProducto.setContentAreaFilled(false);
        btn_RegistrarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_RegistrarProducto.setDefaultCapable(false);
        btn_RegistrarProducto.setFocusPainted(false);
        btn_RegistrarProducto.setFocusable(false);
        btn_RegistrarProducto.setInheritsPopupMenu(true);
        btn_RegistrarProducto.setRequestFocusEnabled(false);
        btn_RegistrarProducto.setRolloverEnabled(false);
        btn_RegistrarProducto.setVerifyInputWhenFocusTarget(false);
        btn_RegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarProductoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_Inicio/file.png"))); // NOI18N

        btn_inventario.setBackground(new java.awt.Color(226, 115, 150));
        btn_inventario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn_inventario.setForeground(new java.awt.Color(234, 242, 215));
        btn_inventario.setText("> Registrar Compras");
        btn_inventario.setBorder(null);
        btn_inventario.setBorderPainted(false);
        btn_inventario.setContentAreaFilled(false);
        btn_inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inventario.setDefaultCapable(false);
        btn_inventario.setFocusPainted(false);
        btn_inventario.setFocusable(false);
        btn_inventario.setInheritsPopupMenu(true);
        btn_inventario.setRequestFocusEnabled(false);
        btn_inventario.setRolloverEnabled(false);
        btn_inventario.setVerifyInputWhenFocusTarget(false);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });

        btn_largate.setBackground(new java.awt.Color(226, 115, 150));
        btn_largate.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn_largate.setForeground(new java.awt.Color(234, 242, 215));
        btn_largate.setText("> Salir");
        btn_largate.setBorder(null);
        btn_largate.setBorderPainted(false);
        btn_largate.setContentAreaFilled(false);
        btn_largate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_largate.setDefaultCapable(false);
        btn_largate.setFocusPainted(false);
        btn_largate.setFocusable(false);
        btn_largate.setInheritsPopupMenu(true);
        btn_largate.setRequestFocusEnabled(false);
        btn_largate.setRolloverEnabled(false);
        btn_largate.setVerifyInputWhenFocusTarget(false);
        btn_largate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_largateActionPerformed(evt);
            }
        });

        txtPrueba.setEditable(false);
        jScrollPane2.setViewportView(txtPrueba);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_Inicio/pastel.jpeg"))); // NOI18N

        btn_ingredientes.setBackground(new java.awt.Color(226, 115, 150));
        btn_ingredientes.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn_ingredientes.setForeground(new java.awt.Color(234, 242, 215));
        btn_ingredientes.setText("> Consultar Recetas");
        btn_ingredientes.setBorder(null);
        btn_ingredientes.setBorderPainted(false);
        btn_ingredientes.setContentAreaFilled(false);
        btn_ingredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingredientes.setDefaultCapable(false);
        btn_ingredientes.setFocusPainted(false);
        btn_ingredientes.setFocusable(false);
        btn_ingredientes.setInheritsPopupMenu(true);
        btn_ingredientes.setRequestFocusEnabled(false);
        btn_ingredientes.setRolloverEnabled(false);
        btn_ingredientes.setVerifyInputWhenFocusTarget(false);
        btn_ingredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingredientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_RegistrarProducto)
                            .addComponent(btn_largate)
                            .addComponent(btn_inventario)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btn_RegistrarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ingredientes)
                        .addGap(18, 18, 18)
                        .addComponent(btn_inventario))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_largate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void btn_RegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarProductoActionPerformed
       
        String texto= "conexion exitosa";
      registrar_productos uno = new registrar_productos();
      uno.setVisible(true);
       txtPrueba.setText(texto);
       this.setVisible(false);
    }//GEN-LAST:event_btn_RegistrarProductoActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        // TODO add your handling code here:
        String texto= " conexion exitosa";
        compra_inventario dos = new compra_inventario();
        dos.setVisible(true);
        this.setVisible(false);
        txtPrueba.setText(texto);
    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_compras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compras2ActionPerformed
        // TODO add your handling code here:
        String texto= " conexion exitosa";
        txtPrueba.setText(texto);
    }//GEN-LAST:event_btn_compras2ActionPerformed

    private void btn_largateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_largateActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_largateActionPerformed

    private void btn_ingredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingredientesActionPerformed
        
        registrar_recetas zapato = new registrar_recetas ();
        zapato.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btn_ingredientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_RegistrarProducto;
    private javax.swing.JButton btn_compras2;
    private javax.swing.JButton btn_ingredientes;
    private javax.swing.JButton btn_inventario;
    private javax.swing.JButton btn_largate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane txtPrueba;
    // End of variables declaration//GEN-END:variables
}
